language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t mikabusante/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikabusante/docker-react npm run test